title = "Rust Game Development Working Group"
description = "Stay up to date with the progress and recent developments in the Rust Game Development Working Group."
base_url = "https://gamedev.rs/"
default_language = "en"
compile_sass = true
highlight_code = true
generate_feed = true
feed_filename = "rss.xml"

[extra]
date_format = "%F"

[extra.home]
max_posts = 3

[extra.posts]
show_summaries = false
max_summary_length = 250

[extra.social_links]
twitter = "rust_gamedev"
github = "rust-gamedev"
discord = "j6QJsMd"
rss = "RSS"
